services:
  - type: web
    name: loopdesk
    env: docker
    region: oregon
    build:
      dockerfile: Dockerfile
    envVars:
      - key: PORT
        value: 8000
    healthCheckPath: /
    autoDeploy: true