services:
  - type: web
    name: stackloop-agent
    env: python
    region: mumbai
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      # Apply the ADK fix
      find . -name "functions.py" -type f -exec sed -i "s/function_response_event=function_response_event,/response_event_id=function_response_event.id,\n        function_response=function_response,/" {} \;
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONDONTWRITEBYTECODE
        value: 1